
import React from 'react';
import { ZakatCalculation, IslamicNote } from '../types';

interface ResultDisplayProps {
  calculation: ZakatCalculation | null;
  note: IslamicNote | null;
  loading: boolean;
  currencySymbol: string;
}

const ResultDisplay: React.FC<ResultDisplayProps> = ({ calculation, note, loading, currencySymbol }) => {
  const exportToTxt = () => {
    if (!calculation) return;
    const content = `
MUHASIB - ZAKAT CALCULATION REPORT
----------------------------------
Date: ${new Date().toLocaleDateString()}
Total Wealth: ${currencySymbol} ${calculation.earnings.toLocaleString()}
Nisab Threshold: ${currencySymbol} ${calculation.nisab.toLocaleString()}
Status: ${calculation.isApplicable ? 'ELIGIBLE' : 'BELOW THRESHOLD'}
Zakat Due: ${currencySymbol} ${calculation.zakatAmount.toLocaleString()}

Note: ${note?.content || 'N/A'}
Ref: ${note?.reference || 'N/A'}

Sources: ${calculation.sources?.join(', ') || 'Manual Input'}

Generated by Muhasib - Islamic Zakat Calculator
    `;
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Muhasib_Zakat_${new Date().toISOString().split('T')[0]}.txt`;
    link.click();
  };

  if (loading) {
    return (
      <div className="bg-slate-800/50 p-8 rounded-2xl border border-slate-700 shadow-2xl flex flex-col items-center justify-center space-y-4 min-h-[300px] animate-pulse">
        <div className="w-16 h-16 bg-slate-700 rounded-full"></div>
        <div className="h-4 bg-slate-700 w-48 rounded"></div>
        <div className="h-4 bg-slate-700 w-32 rounded"></div>
      </div>
    );
  }

  if (!calculation) return null;

  return (
    <div className="bg-slate-800/80 backdrop-blur-sm p-8 rounded-2xl border border-slate-700 shadow-2xl space-y-6 animate-in fade-in zoom-in-95 duration-500">
      <div className="text-center space-y-2">
        <h3 className="text-slate-400 font-bold uppercase tracking-widest text-[10px]">Calculation Output</h3>
        <div className={`inline-block px-4 py-1 rounded-full text-xs font-black tracking-widest uppercase ${calculation.isApplicable ? 'bg-emerald-900/50 text-emerald-400 border border-emerald-800' : 'bg-slate-700/50 text-slate-400 border border-slate-600'}`}>
          {calculation.isApplicable ? 'Zakat Obligatory' : 'Below Threshold'}
        </div>
      </div>

      <div className="flex flex-col items-center justify-center py-6 border-y border-slate-700/50">
        <span className="text-slate-500 text-xs font-bold uppercase tracking-wider mb-2">Calculated Zakat Amount</span>
        <div className="flex items-baseline space-x-2">
          <span className="text-2xl font-bold text-slate-600">{currencySymbol}</span>
          <span className="text-7xl font-black text-white drop-shadow-sm">
            {calculation.zakatAmount.toLocaleString(undefined, { minimumFractionDigits: 0, maximumFractionDigits: 0 })}
          </span>
        </div>
      </div>

      <div className="grid grid-cols-2 gap-4">
        <div className="bg-slate-900/50 p-4 rounded-xl border border-slate-700">
          <p className="text-[10px] text-slate-500 font-bold uppercase mb-1">Current Nisab</p>
          <p className="font-bold text-slate-300">{currencySymbol} {calculation.nisab.toLocaleString()}</p>
        </div>
        <div className="bg-slate-900/50 p-4 rounded-xl border border-slate-700">
          <p className="text-[10px] text-slate-500 font-bold uppercase mb-1">Applied Rate</p>
          <p className="font-bold text-emerald-500">2.5% (1/40)</p>
        </div>
      </div>

      {calculation.sources && calculation.sources.length > 0 && (
        <div className="space-y-2">
          <p className="text-[10px] text-slate-500 font-bold uppercase tracking-widest">Verified Rate Sources</p>
          <div className="flex flex-wrap gap-2">
            {calculation.sources.map((url, i) => (
              <a 
                key={i} 
                href={url} 
                target="_blank" 
                rel="noopener noreferrer"
                className="text-[10px] bg-slate-900 hover:bg-emerald-950 px-3 py-1 rounded-full border border-slate-700 text-emerald-500 transition-colors truncate max-w-[150px]"
              >
                {new URL(url).hostname}
              </a>
            ))}
          </div>
        </div>
      )}

      {note && (
        <div className="bg-emerald-950/30 p-6 rounded-2xl border border-emerald-900/50 relative overflow-hidden">
          <p className="text-emerald-100 font-amiri text-2xl italic relative z-10 leading-relaxed mb-3">
            "{note.content}"
          </p>
          {note.reference && (
            <p className="text-emerald-500 text-xs font-black uppercase tracking-[0.2em] relative z-10">— {note.reference}</p>
          )}
        </div>
      )}

      <button 
        onClick={exportToTxt}
        className="w-full py-4 bg-slate-700 hover:bg-slate-600 text-white font-bold rounded-xl transition-all flex items-center justify-center space-x-2 group"
      >
        <svg className="w-5 h-5 group-hover:translate-y-0.5 transition-transform" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
        </svg>
        <span>Export Result (TXT)</span>
      </button>
    </div>
  );
};

export default ResultDisplay;
